### ISSUE TITLE
property

### ISSUE THREAD

**Issue by antgubarev** [enchikiben/YandexMaps#3]
Полезный весьма виджет, но есть один недочет. Реализованы свойства, но не реализованы опции маркеров. Нельзя например сделать его передвигпемым

**Comment by enchikiben** [comment]
уже можно :)

**Comment by antgubarev** [comment]
я уже тоже допилил:) сейчас теперь еще события делаю

**Comment by porcelanosa** [comment]
События - очень важно, что бы можно было использовать как виджет для указания координат. Спасибо за Вашу работу.

**Comment by kalinichenko88** [comment]
События  - очень нужны, особенно вместе с перемещением маркера для сохранения координат.
Для этих целей можно было бы передавать в скрипт имена полей для координат и там уже генерировать код вида:

 myPlacemark.events.add('dragend', function(){
                                $('#FieldName').val(this.geometry.getCoordinates().toString());
                            },myPlacemark);

Это не так важно можно конечно задать событие

'placemark' => array(
'events'=>array(
'dragend'=>'$("#FieldName").val(this.geometry.getCoordinates().toString()',
)
)

**Comment by enchikiben** [comment]
Скоро будут готовы события

**Comment by antgubarev** [comment]
я сделал по-другому.
перечисляются названия событий и имена клиентских функций, которые из будут обрабатывать. В эту функцию передаются все необходимые данные (например, координаты).
Я всегда работал с свн и не знаю как теперь это все сюда залить :)
