### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by saiprex** [enchikiben/YandexMaps#6]
В методе run() при генерации div'a командой
echo CHtml::tag('div',$this->htmlOptions); 
не генерируется закрывающий тэг </div>. 
Чтобы было всё ок надо писать так 
echo CHtml::tag('div',$this->htmlOptions,''); 

и Спасибо за виждет! Очень кстати попался :)

**Comment by enchikiben** [comment]
Почему не генерирует? насколько вижу в 4 параметр этого метода true отвечает за генерация закрытого тега.

**Comment by saiprex** [comment]
public static function tag($tag,$htmlOptions=array(),$content=false,$closeTag=true)
{
    $html='<' . $tag . self::renderAttributes($htmlOptions);
    if($content===false)
        return $closeTag && self::$closeSingleTags ? $html.' />' : $html.'>';
    else
        return $closeTag ? $html.'>'.$content.'</'.$tag.'>' : $html.'>'.$content;
}

В исходнике видно что происходит когда не указан $content

**Comment by enchikiben** [comment]
поправил :)
